name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:

# منع تشغيل نشرين لنفس الفرع في آنٍ واحد
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      # فحوصنا الموحّدة: validate-wrapper + filenames + imports + i18n + ... الخ
      - name: Verify
        run: npm run verify

      - name: Build
        run: npm run build

      # فحص إضافي بعد البناء لضمان سلامة الحزمة (يقرأ validate-dist-paths.js عبر الـ wrapper)
      - name: Post-build check
        run: node scripts/checks/validate-dist-wrapper.js

      # نرفع الـ dist كـ Artifact (يسهّل استعراض الناتج عند الفشل أو استخدامه في Job النشر)
      - name: Upload dist artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist
          retention-days: 7

  deploy:
    needs: verify_build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install (tools for firebase cli)
        run: npm ci

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          npx firebase-tools deploy \
            --non-interactive \
            --token "$FIREBASE_TOKEN" \
            --project "$FIREBASE_PROJECT_ID" \
            --only hosting
